---
title: Thistle School of English, Αγγλικά - Ενήλικες - Χαλκίδα
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@thistlelanguage.com
description: English for adults and children at Chalkida, Αγγλικά - Ενήλικες - Χαλκίδα
baseurl: ''
url: http://thistlelanguage.com//
twitter_username: jekyllrb
github_username: jekyll
google_analytics: UA-105700036-1
exclude:
- Gemfile
- Gemfile.lock
- Guardfile
- README.md
