---
title: Thistle Language School
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@thistlelanguage.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: ''
url: https://dimitrisdovinos.github.io/thistlelanguage.com/
twitter_username: jekyllrb
github_username: jekyll
google_analytics: UA-105700036-1
exclude:
- Gemfile
- Gemfile.lock
- Guardfile
- README.md
