---
title: Thistle School of English
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@thistlelanguage.com
description: English for adults and children at Chalkida
baseurl: ''
url: https://dimitrisdovinos.github.io/thistlelanguage.com/
twitter_username: jekyllrb
github_username: jekyll
google_analytics: UA-105700036-1
exclude:
- Gemfile
- Gemfile.lock
- Guardfile
- README.md
